"""empty message

Revision ID: a7bca515a457
Revises: ed657e16ce20
Create Date: 2017-06-30 14:59:02.085857

"""

# revision identifiers, used by Alembic.
revision = 'a7bca515a457'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
